# Generated by Django 3.1.7 on 2021-05-05 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craigslistCloneApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'Searches'},
        ),
    ]
