# Generated by Django 3.2.6 on 2022-04-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craigslistCloneApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name': 'Search', 'verbose_name_plural': 'Searches'},
        ),
        migrations.RemoveField(
            model_name='search',
            name='search',
        ),
        migrations.AddField(
            model_name='search',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at '),
        ),
        migrations.AlterField(
            model_name='search',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at '),
        ),
        migrations.AlterField(
            model_name='search',
            name='max_price',
            field=models.CharField(max_length=100, verbose_name='Maximum Price'),
        ),
        migrations.AlterField(
            model_name='search',
            name='min_price',
            field=models.CharField(max_length=100, verbose_name='Minimum Price'),
        ),
    ]
