# Generated by Django 3.2.6 on 2022-04-28 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craigslistCloneApp', '0002_auto_20210505_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='created',
            new_name='created_at',
        ),
    ]
